<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "162.241.218.151");
if (!defined("PJ_USER")) define("PJ_USER", "maltafir_yourcar");
if (!defined("PJ_PASS")) define("PJ_PASS", "Tismalta555");
if (!defined("PJ_DB")) define("PJ_DB", "maltafir_rentscript");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_USE_IV")) define("PJ_USE_IV", "0");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/rent/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home1/maltafir/public_html/yourcarhiremalta/rent/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://yourcarhiremalta.com/rent/");
if (!defined("PJ_SALT")) define("PJ_SALT", "4KGG7M3O");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "NDk4MDY1MTcwMzg5ODY4NzE0NTQxNjU4MzYxMzI3NjE0MzA5MTAwMzE1NjM3MjYwMjY1MjU2NDM1NTc1NzgwMzI1NDU2MDE2NTQzMDI0OTg4NDQ2ODAzNTQ5NTU1NjI0MTkwIDEwODk4NzQ0MDg3NDc3OTYwNTg0NjYzNjc3Nzk4NzMyNTk1MDQxMDEyMjMxNDA2MDE5MDQ3MDE0NjMzMDA3NjYyMjUwMDg3ODQxMzQyMjE5NDYwMTU4MTMyNTgzNTI2Njc4NjUgMTA0OTUwMDMwOTU0NTE0OTQ4OTA4MDQ1OTM1NDE3MzYwMDk5MzQwMjkxODA4MjE5OTA3MDYzOTE5MjQyMjU2MzEzNDQ0NDM3Mzc2ODQ2OTU1NTIyNDAyMzMyMzc1MDAwMzQyMSAzNjQ5MDE2MjQ3MzE3MDI2NjUyMTU1NTI1Nzc5MjAwOTQyMzk4OTM5Nzg2NzQyNjcxMjI1NzA3MDEzNTYzOTI5MjQxOTU0NDE5OTI2MzEyNzkyNjUxMTIyODAxNjEwNDI1MSAyMDk2Mjk2ODk2ODIzMjY2MjUyNjc3Mjg4ODI1NjY2NjM5MDQ3NTA0NTMwMzc4NTMyNTU4NzQ3ODgwNDk4NDc5Nzg5NDUzNDA2Nzg3Mzc2MTc0NTUxOTE1NjA3NDMyNzk3NjUgNjg2MDAyMjAzODAwOTk5NDgxOTkzMzAwMDk4NDU4ODg4ODEyMTcwOTg1NTc0NTg5NzU4ODA5NzQ1MjUwNzM4MDYzODQyNTkwODcyODk2Mjk0MjU2MTg4NTU1NTA4MjExOTc4IDE4NTczMzQ0NjYyMTU3ODczNDk0NjEwNjkzMzY2ODk2NjA0OTA5NTAyNjAwNjkyOTM4Mjg1MTczMTIyNzQ1NDMyNjA1MzQyOTI3NjQ4ODgyNTAwOTgwNTg4NjQ2NDQ2MTUxOA==");
?>